### ISSUE TITLE
Could you please update for https://prayut.click/

### ISSUE THREAD

**Issue by momsamyoi** [tawan475/popcat-TH#9]
Thanks for coding.

Hit yut.

**Comment by tawan475** [comment]
Here's a simple script that replay the request every 30 seconds
```js
setInterval(() => {
    fetch("https://api.prayut.click/clicks", {
      "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-language": "en-US,en;q=0.9,th;q=0.8,hu;q=0.7",
        "content-type": "application/json;charset=UTF-8",
        "sec-ch-ua": "\"Chromium\";v=\"92\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"92\"",
        "sec-ch-ua-mobile": "?0",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site"
      },
      "referrer": "https://prayut.click/",
      "referrerPolicy": "strict-origin-when-cross-origin",
      "body": JSON.stringify({
        g: 12,
        n: 2000,
        t: String(Date.now())
      }),
      "method": "POST",
      "mode": "cors",
      "credentials": "omit"
    }).then(response => response.json())
      .then(data => console.log(data))
      .catch(function(err) {
        console.error(err);
    })
}, 30000)
```

**Comment by momsamyoi** [comment]
I've adjust your script to added key-value "g" in JSON string because prayut.click have "Guild" system.

setInterval(() => {
    fetch("https://api.prayut.click/clicks", {
      "headers": {
        "accept": "application/json, text/plain, */*",
        "accept-language": "en-US,en;q=0.9,th;q=0.8,hu;q=0.7",
        "content-type": "application/json;charset=UTF-8",
        "sec-ch-ua": "\"Chromium\";v=\"92\", \" Not A;Brand\";v=\"99\", \"Google Chrome\";v=\"92\"",
        "sec-ch-ua-mobile": "?0",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site"
      },
      "referrer": "https://prayut.click/",
      "referrerPolicy": "strict-origin-when-cross-origin",
      "body": JSON.stringify({
        n: 3000,
        g: 80,
        t: String(Date.now())
      }),
      "method": "POST",
      "mode": "cors",
      "credentials": "omit"
    }).then(response => response.json())
      .then(data => console.log(data))
      .catch(function(err) {
        console.error(err);
    })
}, 30000)

Thanks for good script
